### ISSUE TITLE
use `gfm-code-blocks` for the gfm

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/tokenize-comment#1]
https://github.com/jonschlinkert/gfm-code-blocks

At all - Good job, finally progress :D

**Comment by jonschlinkert** [comment]
I don't think it's necessary since this is more accurate and already handles gfm code blocks. However, I was thinking that maybe I should update the gfm-code-blocks lib to be smarter. I just ran into [a situation that gfm-code-blocks fails on](https://github.com/jonschlinkert/tokenize-comment/commit/ab61b561d67ffc35a0eb6222281ec6b85129c136#diff-04c6e90faac2675aa89e2176d2eec7d8L202). 

That's what caused the weird formatting. gfm-code-blocks was trying to parse those nested blocks in the example.

> Good job, finally progress :D

thanks! I'll be pushing up something much more interesting soon :)

**Comment by tunnckoCore** [comment]
> However, I was thinking that maybe I should update the gfm-code-blocks lib to be smarter.

Yea, if current is better than it, update the `gfm-code-blocks` and use it back here.

> thanks! I'll be pushing up something much more interesting soon :)

cool to hear!

**Comment by jonschlinkert** [comment]
Hey I'm going to close, I don't think we want to use `gfm-code-blocks` for this. If you think about it, that only does the `gfm` variety of code examples (of course), but since we also need to recognize javadoc and indented, the parsing logic is already here to do gfm. Plus, I would have to figure out a good way to merge in whatever is returned from gfm-code-blocks, which seems like it would be clunky. 

We can revisit in the future if it makes sense. thanks
